"""
Build data/regulatory_pulse.json — sourced regulatory change feed (Feature 5).

Every item requires sourceUrl and sourceLabel. Run via CI / npm prebuild.
"""

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DATA = ROOT / "data" / "regulatory_pulse.json"
OUT_PUBLIC = ROOT / "public" / "data" / "regulatory_pulse.json"

DISCLAIMER = (
    "Regulatory Pulse is informational only — not legal, tax, accounting, or compliance advice. "
    "Confirm requirements with qualified counsel and official agency guidance."
)

INDUSTRIES = (
    "SaaS",
    "Fintech",
    "E-commerce",
    "Healthcare",
    "Marketplace",
    "General",
)


def item(
    id_: str,
    state_abbr: str,
    title: str,
    summary: str,
    effective_date: str,
    industries: list[str],
    source_url: str,
    source_label: str,
    published_at: str,
) -> dict:
    return {
        "id": id_,
        "stateAbbr": state_abbr,
        "title": title,
        "summary": summary,
        "effectiveDate": effective_date,
        "industries": industries,
        "sourceUrl": source_url,
        "sourceLabel": source_label,
        "publishedAt": published_at,
    }


# Hand-curated high-impact regulatory changes — official or reputable sources only.
PULSE_ITEMS: list[dict] = [
    # California (8)
    item(
        "ca-cpra-2023",
        "CA",
        "California Privacy Rights Act (CPRA) operational rules",
        "CPRA expands CCPA with new consumer rights, sensitive data limits, and contractor/service-provider obligations for businesses meeting thresholds.",
        "2023-01-01",
        ["SaaS", "E-commerce", "Marketplace"],
        "https://oag.ca.gov/privacy/ccpa",
        "California Attorney General — CCPA/CPRA",
        "2022-11-01",
    ),
    item(
        "ca-cppa-regulations-2023",
        "CA",
        "CPPA final CPRA regulations",
        "California Privacy Protection Agency regulations clarify opt-out signals, audits, cybersecurity, and automated decision-making disclosures.",
        "2023-03-29",
        ["SaaS", "Fintech"],
        "https://cppa.ca.gov/regulations/",
        "California Privacy Protection Agency",
        "2023-03-15",
    ),
    item(
        "ca-sb253-climate-disclosure",
        "CA",
        "Climate corporate disclosure (SB 253)",
        "Large U.S. companies doing business in California must disclose Scope 1–3 greenhouse gas emissions with third-party assurance phases.",
        "2026-01-01",
        ["General"],
        "https://ww2.arb.ca.gov/our-work/programs/carb-onboarding/california-climate-related-financial-risk-act-sb-261-and-greenhouse",
        "California Air Resources Board",
        "2024-09-01",
    ),
    item(
        "ca-sb261-climate-risk",
        "CA",
        "Climate-related financial risk reporting (SB 261)",
        "Qualifying entities must biennially report climate-related financial risks and mitigation measures under CARB oversight.",
        "2026-01-01",
        ["Fintech", "General"],
        "https://ww2.arb.ca.gov/our-work/programs/carb-onboarding/california-climate-related-financial-risk-act-sb-261-and-greenhouse",
        "California Air Resources Board",
        "2024-09-01",
    ),
    item(
        "ca-fast-act-2024",
        "CA",
        "Fast food minimum wage & council framework (AB 1228)",
        "California fast-food workers receive a higher statewide minimum wage; sector council authority was narrowed after referendum.",
        "2024-04-01",
        ["Marketplace", "General"],
        "https://www.dir.ca.gov/dlse/Fast-Food-Minimum-Wage-FAQ.htm",
        "California Department of Industrial Relations",
        "2024-03-01",
    ),
    item(
        "ca-data-broker-registry",
        "CA",
        "Data broker registration with CPPA",
        "Businesses that sell personal information they did not collect directly must register with the CPPA and pay an annual fee.",
        "2024-01-01",
        ["SaaS", "E-commerce"],
        "https://cppa.ca.gov/data_broker_registry/",
        "California Privacy Protection Agency",
        "2023-12-01",
    ),
    item(
        "ca-delete-act-2026",
        "CA",
        "DELETE Act — one-stop data broker deletion (signed)",
        "Creates a CPPA-operated mechanism for consumers to request deletion across registered data brokers, with phased compliance.",
        "2026-01-01",
        ["SaaS", "E-commerce"],
        "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB362",
        "California Legislative Information — SB 362",
        "2023-10-01",
    ),
    item(
        "ca-ccpa-employee-b2b-sunset",
        "CA",
        "Employee & B2B CCPA exemptions expired",
        "Personal information collected in employment and certain B2B contexts is fully covered by CCPA/CPRA after exemption sunset.",
        "2023-01-01",
        ["General", "SaaS"],
        "https://oag.ca.gov/privacy/ccpa",
        "California Attorney General — CCPA/CPRA",
        "2022-12-01",
    ),
    # New York (7)
    item(
        "ny-shield-act",
        "NY",
        "NY SHIELD Act data security requirements",
        "Businesses holding private information of NY residents must implement reasonable administrative, technical, and physical safeguards.",
        "2020-03-21",
        ["SaaS", "Fintech", "Healthcare"],
        "https://www.dfs.ny.gov/consumers/identity_theft/shield_act_faqs",
        "New York Department of Financial Services",
        "2020-02-01",
    ),
    item(
        "ny-prenatal-leave-2025",
        "NY",
        "Paid prenatal personal leave",
        "New York employees may take paid leave for prenatal healthcare appointments under the paid sick leave law.",
        "2025-01-01",
        ["General"],
        "https://dol.ny.gov/paid-prenatal-leave",
        "New York Department of Labor",
        "2024-11-01",
    ),
    item(
        "nyc-ll144-ai-hiring",
        "NY",
        "NYC Local Law 144 — automated employment decision tools",
        "NYC employers using AI for hiring must conduct annual bias audits and provide candidate notices.",
        "2023-07-05",
        ["SaaS", "General"],
        "https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page",
        "NYC Department of Consumer and Worker Protection",
        "2023-04-01",
    ),
    item(
        "ny-bitlicense",
        "NY",
        "BitLicense virtual currency business regulation",
        "Virtual currency businesses serving New York generally need a BitLicense or limited-purpose trust charter from NY DFS.",
        "2015-06-24",
        ["Fintech"],
        "https://www.dfs.ny.gov/virtual_currency_businesses",
        "New York Department of Financial Services",
        "2015-06-01",
    ),
    item(
        "ny-paid-sick-leave",
        "NY",
        "Statewide paid sick leave",
        "Employers must provide paid sick leave accrual based on employer size; covers diagnosis, care, and domestic violence leave.",
        "2021-01-01",
        ["General", "Marketplace"],
        "https://dol.ny.gov/paid-sick-leave",
        "New York Department of Labor",
        "2020-12-01",
    ),
    item(
        "ny-stop-hacks-act",
        "NY",
        "Stop Hacks and Improve Electronic Data Security (SHIELD) breach notification",
        "Expanded breach notification and security program requirements for NY residents' private information.",
        "2020-03-21",
        ["SaaS", "Healthcare"],
        "https://www.dfs.ny.gov/consumers/identity_theft/shield_act_faqs",
        "New York Department of Financial Services",
        "2020-02-01",
    ),
    item(
        "ny-data-broker-registration",
        "NY",
        "Data broker registration (NY privacy law)",
        "Data brokers meeting definition must register with the NY Attorney General and maintain a consumer opt-out.",
        "2025-03-01",
        ["SaaS", "E-commerce"],
        "https://ag.ny.gov/resources/organizations/data-brokers",
        "New York Attorney General",
        "2024-12-01",
    ),
    # Texas (6)
    item(
        "tx-tdpsa-2024",
        "TX",
        "Texas Data Privacy and Security Act (TDPSA)",
        "Texas privacy law applies to many businesses without revenue thresholds; requires privacy notices, opt-outs, and data protection assessments.",
        "2024-07-01",
        ["SaaS", "E-commerce", "Fintech"],
        "https://www.texasattorneygeneral.gov/consumer-protection/file-consumer-complaint/consumer-privacy-rights/texas-data-privacy-and-security-act",
        "Texas Attorney General",
        "2024-06-01",
    ),
    item(
        "tx-business-courts",
        "TX",
        "Texas business courts for complex commercial cases",
        "Dedicated business court divisions handle large commercial disputes with specialized judges in major counties.",
        "2024-09-01",
        ["General", "Fintech"],
        "https://www.txcourts.gov/business-court/",
        "Texas Judicial Branch — Business Court",
        "2024-08-01",
    ),
    item(
        "tx-franchise-tax-threshold",
        "TX",
        "Texas franchise tax no-tax-due threshold",
        "Entities below the annualized total revenue threshold may file a no-tax-due report instead of owing franchise tax.",
        "2024-01-01",
        ["General"],
        "https://comptroller.texas.gov/taxes/franchise/",
        "Texas Comptroller of Public Accounts",
        "2024-01-01",
    ),
    item(
        "tx-data-breach-notification",
        "TX",
        "Texas Identity Theft Enforcement and Protection Act updates",
        "Businesses must notify Texas residents of breaches of sensitive personal information and report large breaches to the AG.",
        "2020-01-01",
        ["SaaS", "Healthcare"],
        "https://www.texasattorneygeneral.gov/consumer-protection/identity-theft-and-privacy/data-breaches",
        "Texas Attorney General",
        "2019-12-01",
    ),
    item(
        "tx-capture-or-use-biometric",
        "TX",
        "Texas Capture or Use of Biometric Identifier Act (CUBI)",
        "Requires informed consent before capturing biometric identifiers and limits retention and disclosure.",
        "2009-09-01",
        ["SaaS", "General"],
        "https://statutes.capitol.texas.gov/Docs/BC/htm/BC.503.htm",
        "Texas Legislature — Business & Commerce Code Ch. 503",
        "2009-09-01",
    ),
    item(
        "tx-sales-tax-saas",
        "TX",
        "Texas sales tax on data processing & SaaS",
        "Certain cloud, SaaS, and data processing services are taxable in Texas when provided for consideration.",
        "2000-01-01",
        ["SaaS", "E-commerce"],
        "https://comptroller.texas.gov/taxes/publications/94-127.php",
        "Texas Comptroller — Data Processing Services",
        "2023-06-01",
    ),
    # Washington (6)
    item(
        "wa-mhmda-2024",
        "WA",
        "My Health My Data Act (MHMDA)",
        "Broad consumer health data privacy law with consent, geofencing, and deletion rights — beyond HIPAA-covered entities.",
        "2024-03-31",
        ["Healthcare", "SaaS"],
        "https://www.atg.wa.gov/consumer-tips/my-health-my-data-act",
        "Washington Attorney General",
        "2024-02-01",
    ),
    item(
        "wa-cares-fund",
        "WA",
        "WA Cares long-term care benefit",
        "Most Washington workers contribute to a state long-term care insurance benefit; exemptions exist for out-of-state workers.",
        "2023-07-01",
        ["General"],
        "https://wacaresfund.wa.gov/",
        "Washington State WA Cares Fund",
        "2023-06-01",
    ),
    item(
        "wa-climate-commitment-act",
        "WA",
        "Climate Commitment Act cap-and-invest",
        "Large emitters must obtain allowances for greenhouse gas emissions; affects energy-intensive operations.",
        "2023-01-01",
        ["General", "E-commerce"],
        "https://ecology.wa.gov/air-climate/climate-change/climate-commitment-act",
        "Washington Department of Ecology",
        "2022-12-01",
    ),
    item(
        "wa-paid-family-leave",
        "WA",
        "Paid Family and Medical Leave (PFML)",
        "Employers and employees fund statewide paid leave for medical and family events; reporting required for covered employers.",
        "2020-01-01",
        ["General", "Marketplace"],
        "https://paidleave.wa.gov/employers/",
        "Washington Paid Family & Medical Leave",
        "2019-12-01",
    ),
    item(
        "wa-breach-notification",
        "WA",
        "Washington data breach notification",
        "Entities must notify affected Washington residents and the Attorney General when personal information is compromised.",
        "2020-03-01",
        ["SaaS", "Healthcare"],
        "https://www.atg.wa.gov/data-breach-notifications",
        "Washington Attorney General",
        "2019-11-01",
    ),
    item(
        "wa-noncompete-threshold",
        "WA",
        "Noncompete agreement income thresholds",
        "Noncompetes are void for employees below statutory earnings thresholds and banned for certain workers.",
        "2020-01-01",
        ["General", "SaaS"],
        "https://lni.wa.gov/workers-rights/your-rights/non-compete-agreements",
        "Washington Department of Labor & Industries",
        "2019-12-01",
    ),
    # Florida (6)
    item(
        "fl-digital-bill-of-rights-2024",
        "FL",
        "Florida Digital Bill of Rights (scaled)",
        "Privacy rights for consumers against large tech platforms; scope narrowed from original proposal — verify applicability thresholds.",
        "2024-07-01",
        ["SaaS", "E-commerce"],
        "https://www.flsenate.gov/Session/Bill/2024/262",
        "Florida Senate — CS/HB 3 (2024)",
        "2024-06-01",
    ),
    item(
        "fl-economic-nexus-tax",
        "FL",
        "Florida corporate income tax economic nexus",
        "Out-of-state corporations with substantial Florida sales may owe corporate income tax even without physical presence.",
        "2019-01-01",
        ["E-commerce", "SaaS"],
        "https://floridarevenue.com/taxes/taxesfees/Pages/corporate.aspx",
        "Florida Department of Revenue",
        "2023-01-01",
    ),
    item(
        "fl-sales-tax-marketplace",
        "FL",
        "Marketplace facilitator sales tax collection",
        "Marketplace providers must collect and remit Florida sales tax on facilitated sales.",
        "2021-07-01",
        ["Marketplace", "E-commerce"],
        "https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx",
        "Florida Department of Revenue",
        "2021-06-01",
    ),
    item(
        "fl-data-breach-notification",
        "FL",
        "Florida Information Protection Act (FIPA)",
        "Businesses must notify Floridians and regulators of data breaches involving personal information within 30 days.",
        "2014-07-01",
        ["SaaS", "Healthcare"],
        "https://www.myfloridalegal.com/consumer-protection/data-breach",
        "Florida Attorney General",
        "2023-01-01",
    ),
    item(
        "fl-property-insurance-reform",
        "FL",
        "Property insurance market reforms",
        "Legislative packages address assignment of benefits, litigation costs, and Citizens Property Insurance eligibility.",
        "2022-12-01",
        ["General"],
        "https://www.flsenate.gov/Session/Bill/2023/2D",
        "Florida Senate — Special Session SB 2-D",
        "2022-12-01",
    ),
    item(
        "fl-telemarketing-cfpb",
        "FL",
        "Florida Telemarketing Act compliance",
        "Telephone solicitation rules require licensing, calling-hour limits, and Do Not Call compliance for covered sellers.",
        "2024-01-01",
        ["E-commerce", "General"],
        "https://www.myfloridalegal.com/consumer-protection/telemarketing",
        "Florida Attorney General",
        "2023-08-01",
    ),
    # Delaware (4)
    item(
        "de-general-corporation-law",
        "DE",
        "Delaware General Corporation Law updates",
        "Delaware regularly amends DGCL — recent changes affect stockholder rights, fiduciary duties, and entity governance.",
        "2024-08-01",
        ["Fintech", "General"],
        "https://corp.delaware.gov/",
        "Delaware Division of Corporations",
        "2024-07-01",
    ),
    item(
        "de-franchise-tax",
        "DE",
        "Delaware franchise tax & annual report",
        "Delaware-incorporated entities owe annual franchise tax and must file reports by March 1.",
        "2025-03-01",
        ["General", "Fintech"],
        "https://corp.delaware.gov/frtaxcalc/",
        "Delaware Division of Corporations",
        "2025-01-01",
    ),
    item(
        "de-data-breach",
        "DE",
        "Delaware data breach notification law",
        "Persons conducting business in Delaware must notify residents and the Attorney General of qualifying breaches.",
        "2017-04-14",
        ["SaaS"],
        "https://attorneygeneral.delaware.gov/fraud/cpu/security_breach/",
        "Delaware Department of Justice",
        "2017-04-01",
    ),
    item(
        "de-benefit-corporation",
        "DE",
        "Public benefit corporation statutes",
        "Delaware allows public benefit corporations with expanded director duties to stakeholders beyond stockholders.",
        "2013-08-01",
        ["General"],
        "https://corp.delaware.gov/benefitcorp/",
        "Delaware Division of Corporations",
        "2023-01-01",
    ),
    # Illinois (4)
    item(
        "il-bipa",
        "IL",
        "Biometric Information Privacy Act (BIPA)",
        "Private entities need written consent and a retention policy before collecting fingerprints, face scans, or other biometrics.",
        "2008-10-01",
        ["SaaS", "General"],
        "https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=3004",
        "Illinois General Assembly — BIPA",
        "2008-10-01",
    ),
    item(
        "il-personal-info-protection",
        "IL",
        "Personal Information Protection Act (PIPA)",
        "Illinois requires reasonable security measures and breach notification for personal information.",
        "2006-01-01",
        ["SaaS", "Healthcare"],
        "https://www.illinoisattorneygeneral.gov/consumers/security_breach.html",
        "Illinois Attorney General",
        "2023-01-01",
    ),
    item(
        "il-paid-leave-2024",
        "IL",
        "Paid Leave for All Workers Act",
        "Most Illinois employers must provide paid leave employees can use for any reason, accrued per hour worked.",
        "2024-01-01",
        ["General", "Marketplace"],
        "https://www.illinois.gov/idol/Laws-Rules/CONSOLIDATED/paidleave.html",
        "Illinois Department of Labor",
        "2023-12-01",
    ),
    item(
        "il-artificial-intelligence-video",
        "IL",
        "AI video interview disclosure (IVAA)",
        "Employers using AI to analyze video interviews must notify applicants and explain how AI is used.",
        "2020-01-01",
        ["SaaS", "General"],
        "https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=3987",
        "Illinois General Assembly — IVAA",
        "2019-12-01",
    ),
    # Colorado (3)
    item(
        "co-cpa-2023",
        "CO",
        "Colorado Privacy Act (CPA)",
        "Colorado consumers gain access, correction, deletion, and opt-out rights; controllers need privacy notices and data protection assessments.",
        "2023-07-01",
        ["SaaS", "E-commerce"],
        "https://coag.gov/resources/colorado-privacy-act/",
        "Colorado Attorney General",
        "2023-06-01",
    ),
    item(
        "co-ai-act-2024",
        "CO",
        "Colorado AI Act (SB 24-205)",
        "Developers and deployers of high-risk AI systems face impact assessments, disclosure, and anti-discrimination duties.",
        "2026-02-01",
        ["SaaS", "Fintech"],
        "https://leg.colorado.gov/bills/sb24-205",
        "Colorado General Assembly",
        "2024-05-01",
    ),
    item(
        "co-pay-transparency",
        "CO",
        "Colorado pay transparency in job postings",
        "Employers with Colorado employees must include compensation and benefits in public job postings.",
        "2021-01-01",
        ["General"],
        "https://cdle.colorado.gov/employers/recruiting-hiring/Equal-Pay-for-Equal-Work-Act",
        "Colorado Department of Labor and Employment",
        "2020-12-01",
    ),
    # Massachusetts (3)
    item(
        "ma-noncompete-reform",
        "MA",
        "Massachusetts Noncompetition Agreement Act",
        "Noncompetes must meet garden-leave or consideration requirements and cannot exceed 12 months for most employees.",
        "2018-10-01",
        ["General", "SaaS"],
        "https://www.mass.gov/info-details/massachusetts-noncompetition-agreement-act",
        "Massachusetts Courts",
        "2018-09-01",
    ),
    item(
        "ma-data-breach",
        "MA",
        "Massachusetts data security regulations (201 CMR 17.00)",
        "Businesses holding MA residents' personal information must maintain a written information security program (WISP).",
        "2010-03-01",
        ["SaaS", "Healthcare", "Fintech"],
        "https://www.mass.gov/regulations/201-CMR-1700-standards-for-the-protection-of-personal-information-of-residents-of-the-commonwealth",
        "Massachusetts Office of Consumer Affairs",
        "2010-02-01",
    ),
    item(
        "ma-paid-family-leave",
        "MA",
        "Paid Family and Medical Leave (PFML)",
        "Massachusetts employers and workers fund paid family and medical leave benefits administered by the Department of Family and Medical Leave.",
        "2021-01-01",
        ["General"],
        "https://www.mass.gov/orgs/department-of-family-and-medical-leave",
        "Massachusetts Department of Family and Medical Leave",
        "2020-12-01",
    ),
    # Georgia (3)
    item(
        "ga-sales-tax-marketplace",
        "GA",
        "Georgia marketplace facilitator sales tax",
        "Marketplace facilitators must collect and remit Georgia sales tax on third-party sales.",
        "2020-04-01",
        ["Marketplace", "E-commerce"],
        "https://dor.georgia.gov/taxes/sales-use-tax/marketplace-facilitators",
        "Georgia Department of Revenue",
        "2020-03-01",
    ),
    item(
        "ga-data-breach",
        "GA",
        "Georgia Personal Identity Protection Act",
        "Businesses must notify Georgia residents of unauthorized acquisition of personal information.",
        "2005-05-01",
        ["SaaS"],
        "https://law.georgia.gov/data-breach-notifications",
        "Georgia Attorney General",
        "2022-01-01",
    ),
    item(
        "ga-film-tax-credit",
        "GA",
        "Georgia film & digital entertainment tax credit",
        "Qualified production companies may claim transferable tax credits — relevant for media and content startups.",
        "2008-01-01",
        ["General"],
        "https://georgia.org/industries/entertainment/georgia-film-tv-production",
        "Georgia Department of Economic Development",
        "2024-01-01",
    ),
    # North Carolina (2)
    item(
        "nc-data-breach",
        "NC",
        "North Carolina Identity Theft Protection Act",
        "Businesses must notify NC residents and the Attorney General of security breaches involving personal information.",
        "2005-12-01",
        ["SaaS", "Healthcare"],
        "https://ncdoj.gov/protecting-consumers/data-breaches/",
        "North Carolina Department of Justice",
        "2023-01-01",
    ),
    item(
        "nc-unemployment-overpayment",
        "NC",
        "NC unemployment insurance employer accounts",
        "Employers fund unemployment insurance; new businesses register for NCUI tax accounts when hiring.",
        "2024-01-01",
        ["General"],
        "https://des.nc.gov/employers",
        "North Carolina Division of Employment Security",
        "2024-01-01",
    ),
    # Virginia (2)
    item(
        "va-vcdpa-2023",
        "VA",
        "Virginia Consumer Data Protection Act (VCDPA)",
        "Virginia consumers receive access, correction, deletion, and opt-out rights similar to other state privacy laws.",
        "2023-01-01",
        ["SaaS", "E-commerce"],
        "https://www.oag.state.va.us/consumer-protection/index.php/consumer-privacy",
        "Virginia Attorney General",
        "2022-12-01",
    ),
    item(
        "va-noncompete-ban-low-wage",
        "VA",
        "Virginia ban on noncompetes for low-wage workers",
        "Employers may not enter noncompete agreements with low-wage employees as defined by statute.",
        "2020-07-01",
        ["General"],
        "https://law.lis.virginia.gov/vacode/title40.1/chapter3/section40.1-28.7:8/",
        "Virginia Legislative Information System",
        "2020-06-01",
    ),
    # New Jersey (2)
    item(
        "nj-pay-equity-reporting",
        "NJ",
        "New Jersey pay equity reporting (Diane B. Allen Act)",
        "Certain public contractors must report employee compensation by gender, race, and job category.",
        "2020-07-01",
        ["General"],
        "https://www.nj.gov/treasury/contract_compliance/diane-b-allen-act.shtml",
        "New Jersey Department of the Treasury",
        "2020-06-01",
    ),
    item(
        "nj-data-breach",
        "NJ",
        "New Jersey Identity Theft Prevention Act",
        "Businesses must notify New Jersey residents of breaches of personal information without unreasonable delay.",
        "2005-07-01",
        ["SaaS"],
        "https://www.nj.gov/oag/ge/docs/FAQ-DataBreaches.pdf",
        "New Jersey Office of the Attorney General",
        "2023-01-01",
    ),
    # Additional states (1–2 each to reach corpus size)
    item(
        "ct-ctdpa-2023",
        "CT",
        "Connecticut Data Privacy Act (CTDPA)",
        "Connecticut privacy law grants consumer rights and imposes controller obligations including data protection assessments.",
        "2023-07-01",
        ["SaaS", "E-commerce"],
        "https://portal.ct.gov/AG/Sections/Privacy/The-Connecticut-Data-Privacy-Act",
        "Connecticut Attorney General",
        "2023-06-01",
    ),
    item(
        "ut-ucpa-2023",
        "UT",
        "Utah Consumer Privacy Act (UCPA)",
        "Utah consumers may access, delete, and opt out of sale of personal data; lighter obligations than CPRA for many businesses.",
        "2023-12-31",
        ["SaaS"],
        "https://commerce.utah.gov/privacy/",
        "Utah Department of Commerce",
        "2023-11-01",
    ),
    item(
        "or-ocpa-2024",
        "OR",
        "Oregon Consumer Privacy Act (OCPA)",
        "Oregon privacy law includes consumer rights, universal opt-out, and DPIA requirements for high-risk processing.",
        "2024-07-01",
        ["SaaS", "E-commerce"],
        "https://www.doj.state.or.us/consumer-protection/identity-theft-data-breaches/oregon-consumer-privacy-act/",
        "Oregon Department of Justice",
        "2024-06-01",
    ),
    item(
        "nv-privacy-opt-out",
        "NV",
        "Nevada privacy opt-out for sale of covered information",
        "Consumers may direct operators not to sell certain covered information; operators must provide a designated request method.",
        "2019-10-01",
        ["SaaS", "E-commerce"],
        "https://ag.nv.gov/About/Privacy/Privacy_Requests/",
        "Nevada Attorney General",
        "2019-09-01",
    ),
    item(
        "az-data-breach",
        "AZ",
        "Arizona data breach notification",
        "Entities must notify Arizona residents of unauthorized acquisition of unencrypted personal information.",
        "2018-08-01",
        ["SaaS"],
        "https://www.azag.gov/consumer/data-breach",
        "Arizona Attorney General",
        "2018-07-01",
    ),
    item(
        "mn-privacy-2025",
        "MN",
        "Minnesota Consumer Data Privacy Act",
        "Minnesota joins state privacy patchwork with consumer rights, consent requirements, and contractor obligations.",
        "2025-07-31",
        ["SaaS", "Healthcare"],
        "https://www.ag.state.mn.us/Office/Privacy/DataPrivacy/",
        "Minnesota Attorney General",
        "2024-05-01",
    ),
    item(
        "md-online-privacy-2025",
        "MD",
        "Maryland Online Data Privacy Act (MODPA)",
        "Maryland privacy law restricts sale of sensitive data and sets consumer rights for Maryland residents.",
        "2025-10-01",
        ["SaaS", "Healthcare"],
        "https://www.marylandattorneygeneral.gov/Pages/IdentityTheft/data-breach.aspx",
        "Maryland Attorney General",
        "2024-05-01",
    ),
    item(
        "pa-breach-notification",
        "PA",
        "Pennsylvania breach of personal information notification",
        "Businesses must notify Pennsylvania residents when personal information is disclosed without authorization.",
        "2006-01-01",
        ["SaaS"],
        "https://www.attorneygeneral.gov/protect-yourself/data-breach/",
        "Pennsylvania Office of Attorney General",
        "2023-01-01",
    ),
    item(
        "oh-data-breach",
        "OH",
        "Ohio data breach notification law",
        "Entities must notify Ohio residents of breaches of personal information without unreasonable delay.",
        "2007-02-01",
        ["SaaS"],
        "https://www.ohioattorneygeneral.gov/Individuals-and-Families/Consumers/Data-Breach-Notification",
        "Ohio Attorney General",
        "2023-01-01",
    ),
    item(
        "mi-data-breach",
        "MI",
        "Michigan data breach notification",
        "Businesses must notify Michigan residents and provide notice to the Attorney General for large breaches.",
        "2007-01-01",
        ["SaaS", "Healthcare"],
        "https://www.michigan.gov/ag/initiatives/identity-theft",
        "Michigan Attorney General",
        "2023-01-01",
    ),
    item(
        "wi-data-breach",
        "WI",
        "Wisconsin data breach notification",
        "Businesses must notify Wisconsin residents of unauthorized acquisition of personal information.",
        "2006-05-01",
        ["SaaS"],
        "https://www.wisconsin.gov/Pages/Security/DataBreach.aspx",
        "Wisconsin Department of Administration",
        "2023-01-01",
    ),
    item(
        "in-data-breach",
        "IN",
        "Indiana disclosure of security breach",
        "Businesses must notify Indiana residents of breaches of personal information.",
        "2006-07-01",
        ["SaaS"],
        "https://www.in.gov/attorneygeneral/consumer-protection-division/id-theft-prevention/data-breach/",
        "Indiana Attorney General",
        "2023-01-01",
    ),
    item(
        "mo-data-breach",
        "MO",
        "Missouri data breach notification",
        "Businesses must notify Missouri residents when personal information is compromised.",
        "2009-08-01",
        ["SaaS"],
        "https://ago.mo.gov/docs/default-source/default-document-library/data-breach-notifications.pdf",
        "Missouri Attorney General",
        "2023-01-01",
    ),
    item(
        "tn-data-breach",
        "TN",
        "Tennessee Identity Theft Deterrence Act",
        "Businesses must notify Tennessee residents of unauthorized access to personal information.",
        "2005-07-01",
        ["SaaS"],
        "https://www.tn.gov/attorneygeneral/working-for-tennessee/consumer/data-breach.html",
        "Tennessee Attorney General",
        "2023-01-01",
    ),
    item(
        "sc-data-breach",
        "SC",
        "South Carolina Financial Identity Fraud and Identity Theft Protection Act",
        "Businesses must notify South Carolina residents of security breaches involving personal information.",
        "2008-01-01",
        ["SaaS"],
        "https://www.scag.gov/civil/identity-theft-unit/",
        "South Carolina Attorney General",
        "2023-01-01",
    ),
    item(
        "la-data-breach",
        "LA",
        "Louisiana Database Security Breach Notification Law",
        "Businesses must notify Louisiana residents of breaches of personal information.",
        "2006-01-01",
        ["SaaS"],
        "https://ag.louisiana.gov/Article/5/Security-Breach-Notification",
        "Louisiana Attorney General",
        "2023-01-01",
    ),
    item(
        "al-data-breach",
        "AL",
        "Alabama Data Breach Notification Act",
        "Covered entities must notify Alabama residents and the Attorney General of qualifying data breaches.",
        "2018-06-01",
        ["SaaS"],
        "https://www.alabamaag.gov/consumercomplaint/",
        "Alabama Attorney General",
        "2018-05-01",
    ),
    item(
        "ok-data-breach",
        "OK",
        "Oklahoma Security Breach Notification Act",
        "Businesses must notify Oklahoma residents of unauthorized access to personal information.",
        "2008-11-01",
        ["SaaS"],
        "https://www.oag.ok.gov/identity-theft-and-fraud",
        "Oklahoma Attorney General",
        "2023-01-01",
    ),
    item(
        "ks-data-breach",
        "KS",
        "Kansas breach of consumer security information",
        "Businesses must notify Kansas residents when personal information is acquired without authorization.",
        "2007-01-01",
        ["SaaS"],
        "https://www.ag.ks.gov/in-your-corner-kansas/identity-theft",
        "Kansas Attorney General",
        "2023-01-01",
    ),
    item(
        "ne-data-breach",
        "NE",
        "Nebraska Financial Data Protection and Consumer Notification of Data Security Breach Act",
        "Businesses must notify Nebraska residents of breaches of personal information.",
        "2006-01-01",
        ["SaaS"],
        "https://www.nebraska.gov/ago/consumer-protection/identity-theft/",
        "Nebraska Attorney General",
        "2023-01-01",
    ),
    item(
        "ia-data-breach",
        "IA",
        "Iowa consumer data breach notification",
        "Businesses must notify Iowa residents of unauthorized acquisition of personal information.",
        "2014-07-01",
        ["SaaS"],
        "https://www.iowaattorneygeneral.gov/for-consumers/general-consumer-information/data-breach",
        "Iowa Attorney General",
        "2014-06-01",
    ),
    item(
        "ar-data-breach",
        "AR",
        "Arkansas Personal Information Protection Act",
        "Businesses must notify Arkansas residents of security breaches involving personal information.",
        "2005-08-01",
        ["SaaS"],
        "https://arkansasag.gov/resources/consumer-protection/identity-theft/",
        "Arkansas Attorney General",
        "2023-01-01",
    ),
    item(
        "ms-data-breach",
        "MS",
        "Mississippi data breach notification",
        "Businesses must notify Mississippi residents of breaches of personal information.",
        "2011-07-01",
        ["SaaS"],
        "https://www.ago.state.ms.us/victims/data-breach/",
        "Mississippi Attorney General",
        "2023-01-01",
    ),
    item(
        "nm-data-breach",
        "NM",
        "New Mexico Data Breach Notification Act",
        "Businesses must notify New Mexico residents of security breaches involving personal information.",
        "2017-06-01",
        ["SaaS"],
        "https://www.nmag.gov/consumer-alerts/data-breach.aspx",
        "New Mexico Attorney General",
        "2017-05-01",
    ),
    item(
        "hi-data-breach",
        "HI",
        "Hawaii security breach notification",
        "Businesses must notify Hawaii residents of unauthorized access to personal information.",
        "2006-07-01",
        ["SaaS"],
        "https://ag.hawaii.gov/consumer-protection/security-breach/",
        "Hawaii Office of Consumer Protection",
        "2023-01-01",
    ),
    item(
        "ak-data-breach",
        "AK",
        "Alaska personal information protection Act",
        "Businesses must notify Alaska residents of breaches of personal information.",
        "2009-07-01",
        ["SaaS"],
        "https://law.alaska.gov/department/civil/consumer/cp_index.html",
        "Alaska Department of Law",
        "2023-01-01",
    ),
    item(
        "mt-data-breach",
        "MT",
        "Montana Consumer Data Privacy Act (2023)",
        "Montana privacy law provides consumer rights including opt-out of sale and targeted advertising.",
        "2024-10-01",
        ["SaaS"],
        "https://dojmt.gov/consumer/data-breach/",
        "Montana Department of Justice",
        "2023-05-01",
    ),
    item(
        "id-data-breach",
        "ID",
        "Idaho breach notification law",
        "Businesses must notify Idaho residents of unauthorized acquisition of personal information.",
        "2006-07-01",
        ["SaaS"],
        "https://www.ag.idaho.gov/office-resources/consumer-protection/",
        "Idaho Attorney General",
        "2023-01-01",
    ),
    item(
        "wv-data-breach",
        "WV",
        "West Virginia consumer credit and protection act — breach notification",
        "Businesses must notify West Virginia residents of security breaches involving personal information.",
        "2005-07-01",
        ["SaaS"],
        "https://ago.wv.gov/consumerprotection/Pages/Identity-Theft.aspx",
        "West Virginia Attorney General",
        "2023-01-01",
    ),
    item(
        "ri-data-breach",
        "RI",
        "Rhode Island Identity Theft Protection Act",
        "Businesses must notify Rhode Island residents of breaches of personal information.",
        "2006-06-01",
        ["SaaS"],
        "https://riag.ri.gov/consumer-protection/identity-theft",
        "Rhode Island Attorney General",
        "2023-01-01",
    ),
    item(
        "nh-data-breach",
        "NH",
        "New Hampshire security breach notification",
        "Businesses must notify New Hampshire residents of unauthorized access to personal information.",
        "2006-08-01",
        ["SaaS"],
        "https://www.doj.nh.gov/consumer/identity-theft/index.htm",
        "New Hampshire Department of Justice",
        "2023-01-01",
    ),
    item(
        "me-data-breach",
        "ME",
        "Maine data breach notification",
        "Businesses must notify Maine residents of security breaches involving personal information.",
        "2006-01-01",
        ["SaaS"],
        "https://www.maine.gov/ag/consumer/identity_theft/index.shtml",
        "Maine Attorney General",
        "2023-01-01",
    ),
    item(
        "vt-data-breach",
        "VT",
        "Vermont data broker regulation",
        "Data brokers must register annually with the Vermont Secretary of State and meet minimum data security standards.",
        "2019-01-01",
        ["SaaS", "E-commerce"],
        "https://sos.vermont.gov/data-broker/",
        "Vermont Secretary of State",
        "2018-12-01",
    ),
    item(
        "sd-data-breach",
        "SD",
        "South Dakota breach notification law",
        "Businesses must notify South Dakota residents of breaches of personal information.",
        "2018-07-01",
        ["SaaS"],
        "https://atg.sd.gov/Consumers/IdentityTheft/DataBreaches.aspx",
        "South Dakota Attorney General",
        "2018-06-01",
    ),
    item(
        "nd-data-breach",
        "ND",
        "North Dakota breach notification",
        "Businesses must notify North Dakota residents of unauthorized acquisition of personal information.",
        "2007-08-01",
        ["SaaS"],
        "https://www.ag.nd.gov/consumer-resources/identity-theft",
        "North Dakota Attorney General",
        "2023-01-01",
    ),
    item(
        "wy-data-breach",
        "WY",
        "Wyoming data breach notification",
        "Businesses must notify Wyoming residents of unauthorized acquisition of personal information.",
        "2015-07-01",
        ["SaaS"],
        "https://ag.wyo.gov/consumer-protection",
        "Wyoming Attorney General",
        "2023-01-01",
    ),
    item(
        "ky-data-breach",
        "KY",
        "Kentucky data breach notification",
        "Businesses must notify Kentucky residents of security breaches involving personal information.",
        "2014-07-01",
        ["SaaS"],
        "https://www.ag.ky.gov/Resources/Consumer-Resources/Identity-Theft/Pages/default.aspx",
        "Kentucky Attorney General",
        "2023-01-01",
    ),
]


def build_payload() -> dict:
    sorted_items = sorted(
        PULSE_ITEMS,
        key=lambda row: (row["effectiveDate"], row["stateAbbr"], row["id"]),
        reverse=True,
    )
    return {
        "disclaimer": DISCLAIMER,
        "industries": list(INDUSTRIES),
        "staleAfterDays": 365,
        "lastCuratedAt": date.today().isoformat(),
        "items": sorted_items,
    }


def main() -> None:
    payload = build_payload()
    text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    OUT_DATA.parent.mkdir(parents=True, exist_ok=True)
    OUT_PUBLIC.parent.mkdir(parents=True, exist_ok=True)
    OUT_DATA.write_text(text, encoding="utf-8")
    OUT_PUBLIC.write_text(text, encoding="utf-8")
    print(f"OK: wrote {len(payload['items'])} regulatory pulse items")


if __name__ == "__main__":
    main()
